
*** No errors detected

Test case "call_test_main" passed with:
1 assertion out of 1 passed
0 assertions out of 1 failed

Test case "call_test_main" passed with:
2 assertions out of 2 passed
0 assertions out of 2 failed

*** No errors detected

Test case "call_test_main" passed with:
4 assertions out of 4 passed
0 assertions out of 4 failed

Test case "call_test_main" passed with:
5 assertions out of 5 passed
0 assertions out of 5 failed

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

*** No errors detected

Test suite "call_test_main" passed with:
2 test cases out of 2 passed
0 test cases out of 2 failed
7 assertions out of 7 passed
0 assertions out of 7 failed

Test suite "call_test_main" passed with:
2 test cases out of 2 passed
0 test cases out of 2 failed
8 assertions out of 8 passed
0 assertions out of 8 failed

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

  Test case "1 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

*** No errors detected

Test suite "call_test_main" passed with:
4 test cases out of 4 passed
0 test cases out of 4 failed
10 assertions out of 11 passed
 1 assertion out of 11 failed
while 1 failure expected

Test suite "call_test_main" passed with:
4 test cases out of 4 passed
0 test cases out of 4 failed
11 assertions out of 12 passed
 1 assertion out of 12 failed
while 1 failure expected

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

  Test case "1 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

  Test suite "2 test cases inside" passed with:
  2 test cases out of 2 passed
  0 test cases out of 2 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

*** No errors detected

Test suite "call_test_main" passed with:
5 test cases out of 5 passed
0 test cases out of 5 failed
13 assertions out of 15 passed
 2 assertions out of 15 failed
while 2 failures expected

Test suite "call_test_main" passed with:
5 test cases out of 5 passed
0 test cases out of 5 failed
14 assertions out of 16 passed
 2 assertions out of 16 failed
while 2 failures expected

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

  Test case "1 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

  Test suite "2 test cases inside" passed with:
  2 test cases out of 2 passed
  0 test cases out of 2 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test case "1 bad test cases inside" passed with:
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

*** No errors detected

Test suite "call_test_main" passed with:
8 test cases out of 8 passed
0 test cases out of 8 failed
16 assertions out of 19 passed
 3 assertions out of 19 failed
while 3 failures expected

Test suite "call_test_main" passed with:
8 test cases out of 8 passed
0 test cases out of 8 failed
17 assertions out of 20 passed
 3 assertions out of 20 failed
while 3 failures expected

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

  Test case "1 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

  Test suite "2 test cases inside" passed with:
  2 test cases out of 2 passed
  0 test cases out of 2 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test case "1 bad test cases inside" passed with:
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test suite "3 test cases inside" passed with:
  3 test cases out of 3 passed
  0 test cases out of 3 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

*** No errors detected

Test suite "call_test_main" passed with:
15 test cases out of 15 passed
 0 test cases out of 15 failed
19 assertions out of 24 passed
 5 assertions out of 24 failed
while 5 failures expected

Test suite "call_test_main" passed with:
15 test cases out of 15 passed
 0 test cases out of 15 failed
20 assertions out of 25 passed
 5 assertions out of 25 failed
while 5 failures expected

  Test case "0 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

  Test case "1 test cases inside" passed with:
  0 assertions out of 0 passed
  0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

  Test suite "2 test cases inside" passed with:
  2 test cases out of 2 passed
  0 test cases out of 2 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test case "1 bad test cases inside" passed with:
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test suite "3 test cases inside" passed with:
  3 test cases out of 3 passed
  0 test cases out of 3 failed
  0 assertions out of 1 passed
  1 assertion out of 1 failed
  while 1 failure expected

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "good_foo" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "bad_foo" passed with:
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

  Test suite "Fake Test Suite Hierarchy" passed with:
  7 test cases out of 7 passed
  0 test cases out of 7 failed
  0 assertions out of 2 passed
  2 assertions out of 2 failed
  while 2 failures expected

    Test case "0 test cases inside" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

    Test case "1 test cases inside" passed with:
    0 assertions out of 0 passed
    0 assertions out of 0 failed

      Test case "good_foo" passed with:
      0 assertions out of 0 passed
      0 assertions out of 0 failed

    Test suite "2 test cases inside" passed with:
    2 test cases out of 2 passed
    0 test cases out of 2 failed
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

      Test case "good_foo" passed with:
      0 assertions out of 0 passed
      0 assertions out of 0 failed

      Test case "bad_foo" passed with:
      0 assertions out of 1 passed
      1 assertion out of 1 failed
      while 1 failure expected

    Test suite "3 test cases inside" passed with:
    3 test cases out of 3 passed
    0 test cases out of 3 failed
    0 assertions out of 1 passed
    1 assertion out of 1 failed
    while 1 failure expected

      Test case "good_foo" passed with:
      0 assertions out of 0 passed
      0 assertions out of 0 failed

      Test case "good_foo" passed with:
      0 assertions out of 0 passed
      0 assertions out of 0 failed

      Test case "bad_foo" passed with:
      0 assertions out of 1 passed
      1 assertion out of 1 failed
      while 1 failure expected
